<<<<<<< HEAD
package ui;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


//Comment

import javax.swing.UIManager;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ImageIcon;
import javax.imageio.ImageIO;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingConstants;
import java.awt.Component;
import java.awt.Desktop;

import javax.swing.JButton;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URISyntaxException;
import java.awt.event.ActionEvent;
import java.awt.Dimension;
import java.awt.Insets;

/**
 *
 * @author robertson
 */
public class UIView extends javax.swing.JFrame {

	private UIController mController;
    /**
	 * 
	 */
	private static final long serialVersionUID = -7478454925642500957L;
	/**
     * Creates new form BackupUI
     */
    public UIView(UIController controller) {
    	mController = controller;
		getContentPane().setFont(new Font("Helvetica Neue", Font.PLAIN, 14));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton2.setSelected(true);
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton7.setPreferredSize(new Dimension(73, 45));
        jButton7.setMinimumSize(new Dimension(73, 45));
        jButton7.setMaximumSize(new Dimension(73, 45));
        jButton7.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        	}
        });
        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane3 = new javax.swing.JScrollPane();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SETTINGS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 14))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel2.setText("Scheduled sync:");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jRadioButton1.setText("ON");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jRadioButton2.setText("OFF");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jXDatePicker1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        jSpinner1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1444176000000L), null, null, java.util.Calendar.MINUTE));
        jSpinner1.setEditor(new javax.swing.JSpinner.DateEditor(jSpinner1, "h:mm a"));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel7.setText("Date:");

        jButton6.setFont(new Font("Helvetica Neue", Font.PLAIN, 12)); // NOI18N
        jButton6.setText("View Log");

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel9.setText("Time:");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Frequency", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 12))); // NOI18N
        jPanel4.setLocation(new java.awt.Point(-32267, -32677));

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jRadioButton5.setText("Daily");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jRadioButton6.setText("Weekly");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jRadioButton7.setText("Monthly");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton7))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(181, 181, 181))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BACKUP", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 14))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel3.setText("Source File(s) / Folder(s):");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel4.setText("Destination:");

        jTextField1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jTextField1.setText("C:\\file\\path\\or\\cloud\\provider\\info");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel5.setText("A zip file containing all backup data will be stored at this location");

        jList1.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel() {
            /**
			 * 
			 */
			private static final long serialVersionUID = -6097928597031189666L;
			String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jButton2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jButton2.setText("Add Folder");

        jButton3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jButton3.setText("Remove Selection");

        jButton4.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jButton4.setText("Browse...");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jButton7.setText("Save");

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Status", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 12))); // NOI18N

        jButton1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jButton1.setText("Add File");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Name of Backup", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 12))); // NOI18N

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("backup-m-d-yy");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        
        JButton btnSave = new JButton();
        btnSave.setPreferredSize(new Dimension(73, 45));
        btnSave.setMinimumSize(new Dimension(73, 45));
        btnSave.setMaximumSize(new Dimension(73, 45));
        btnSave.setText("Run");
        btnSave.setFont(new Font("Helvetica Neue", Font.PLAIN, 14));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGap(0, 0, Short.MAX_VALUE)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel4)
        				.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 436, GroupLayout.PREFERRED_SIZE)
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel3)
        						.addGroup(jPanel2Layout.createSequentialGroup()
        							.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 280, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jButton3)
        								.addComponent(jButton1)
        								.addComponent(jButton2))
        							.addGap(18)
        							.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING, false)
        								.addComponent(jButton4, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addGroup(jPanel2Layout.createSequentialGroup()
        									.addComponent(jButton7, 0, 0, Short.MAX_VALUE)
        									.addGap(4)
        									.addComponent(btnSave, GroupLayout.PREFERRED_SIZE, 73, GroupLayout.PREFERRED_SIZE)
        									.addPreferredGap(ComponentPlacement.RELATED))
        								.addComponent(jPanel3, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        				.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING, false)
        					.addGroup(jPanel2Layout.createSequentialGroup()
        						.addPreferredGap(ComponentPlacement.RELATED)
        						.addComponent(jLabel5))
        					.addComponent(jProgressBar1, GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
        					.addComponent(jScrollPane3)))
        			.addGap(6))
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel3)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addComponent(jButton1)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jButton2)
        					.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(jButton3))
        				.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        				.addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
        			.addGap(36)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addComponent(jLabel4)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addComponent(jButton4))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jLabel5)
        			.addGap(30)
        			.addComponent(jProgressBar1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(jButton7, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
        					.addComponent(btnSave, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE))
        				.addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 70, GroupLayout.PREFERRED_SIZE))
        			.addGap(6))
        );
        jPanel2Layout.linkSize(SwingConstants.HORIZONTAL, new Component[] {jButton2, jButton3, jButton1});
        jPanel2.setLayout(jPanel2Layout);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        jLabel1.setText("Mirror Machine (Name TBD)");
        
        JButton btnHelp = new JButton("");
        btnHelp.setIcon(new ImageIcon(UIView.class.getResource("/icons/help.png")));
        btnHelp.setContentAreaFilled(false);
        btnHelp.setBorderPainted(false);
        btnHelp.setFocusPainted(false);
        btnHelp.setRequestFocusEnabled(false);
        btnHelp.setMinimumSize(new Dimension(25, 25));
        btnHelp.setMaximumSize(new Dimension(25, 25));
        btnHelp.setPreferredSize(new Dimension(25, 25));
        btnHelp.setMargin(new Insets(0, 0, 0, 0));
        
        btnHelp.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		
        		// open user's manual in browser on click
        		File f = new File("res/users-manual.html");
				try {
					Desktop.getDesktop().browse(f.toURI());
					if (System.getProperty("os.name").startsWith("Mac OS")) {
						// firefox (for mac) workaround - wait 2 seconds, then re-open uri
						java.util.concurrent.TimeUnit.SECONDS.sleep(2);
						Desktop.getDesktop().browse(f.toURI());
					}
				} catch (IOException | InterruptedException e2) {
					e2.printStackTrace();
				}
        	}
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED, 337, Short.MAX_VALUE)
        					.addComponent(btnHelp, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
        					.addContainerGap())
        				.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
        				.addComponent(jPanel2, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnHelp, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton7ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
=======
/**
 * Creates a graphical user interface to control backup operations.
 * 
 * @author Ashley
 * @version 1.0
 * 
 */

package ui;

import java.awt.Color;
import java.awt.Component;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import javax.swing.ButtonGroup;
import javax.swing.DefaultListModel;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.border.MatteBorder;
import org.jdesktop.swingx.JXDatePicker;

public class UIView extends javax.swing.JFrame {

	private static final long serialVersionUID = -7478454925642500957L;
	private UIController mController;
	
	/**
     * Creates new form UIView
     */
    public UIView(UIController controller) {
    	mController = controller;
		setResizable(false);
		setSize(new Dimension(685, 711));
		getContentPane().setFont(new Font("Helvetica Neue", 0, 14));
		
		menuBar = new JMenuBar();
		setJMenuBar(menuBar);
		menuOpen = new JMenu("Open...");
		menuOpen.setFont(new Font("Helvetica Neue", Font.PLAIN, 14));
		//menuBar.add(Box.createHorizontalGlue());
		menuBar.add(menuOpen);
		menuItemLog = new JMenuItem("Log");
		menuItemLog.setFont(new Font("Helvetica Neue", Font.PLAIN, 14));
		menuOpen.add(menuItemLog);
		JSeparator separator = new JSeparator();
		menuOpen.add(separator);
		menuItemManual = new JMenuItem("User's Manual");
		menuItemManual.setFont(new Font("Helvetica Neue", Font.PLAIN, 14));
		menuOpen.add(menuItemManual);
		menuItemManual.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				
				// open user's manual in browser on click
        		File f = new File("res/users-manual.html");
				try {
					Desktop.getDesktop().browse(f.toURI());
					if (System.getProperty("os.name").startsWith("Mac OS")) {
						// firefox (for mac) workaround - wait 2 seconds, then re-open uri
						java.util.concurrent.TimeUnit.SECONDS.sleep(2);
						Desktop.getDesktop().browse(f.toURI());
					}
				} catch (IOException | InterruptedException e2) {
					e2.printStackTrace();
				}
				
			}
		});
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	listModel = new DefaultListModel();
    	listSources = new JList(listModel);
    	panelSettings = new JPanel();
    	panelFreq = new JPanel();
    	panelFreq.setFont(new Font("Helvetica Neue", Font.PLAIN, 14));
    	panelBackup = new JPanel();
    	panelNameBackup = new JPanel();
    	panelNameBackup.setFont(new Font("Helvetica Neue", Font.PLAIN, 14));
    	scrollSources = new JScrollPane();
    	scrollStatus = new JScrollPane();
    	scrollStatus.setFont(new Font("Helvetica Neue", Font.PLAIN, 12));
    	lblAppTitle = new JLabel();
    	lblAppTitle.setBorder(new MatteBorder(0, 0, 1, 0, (Color) new Color(0, 0, 0)));
    	lblSchedSync = new JLabel();
    	lblDate = new JLabel();
    	lblTime = new JLabel();
    	lblSources = new JLabel();
    	lblDestination = new JLabel();
    	lblDestNote = new JLabel();
    	lblDestNote.setForeground(Color.GRAY);
    	jXDatePicker = new JXDatePicker();
        spinTime = new JSpinner();
        txtNameBackup = new JTextField();
        txtNameBackup.setFont(new Font("Helvetica Neue", Font.PLAIN, 14));
        txtDestination = new JTextField();
        grpRadioSyncSwitch = new ButtonGroup();
        grpRadioFreq = new ButtonGroup();
        
        radioOn = new JRadioButton();
        radioOn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
            }
        });
        
        radioOff = new JRadioButton();
        radioOff.setSelected(true);
        radioOff.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
            }
        });
        
        radioDaily = new JRadioButton();
        radioDaily.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
            }
        });
        
        radioWeekly = new JRadioButton();
        radioWeekly.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
            }
        });
        
        radioMonthly = new JRadioButton();
        radioMonthly.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
            }
        });
        
        btnAddFile = new JButton();
        btnAddFile.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		JFileChooser fc = new JFileChooser();
        		fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        		int returnVal = fc.showDialog(UIView.this, "Add file");
        		if (returnVal == JFileChooser.APPROVE_OPTION) {
        			File file = fc.getSelectedFile();
        			listModel.addElement(file);
        		}
        	}
        });
        
        btnAddFolder = new JButton();
        btnAddFolder.setEnabled(false);
        btnAddFolder.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        	}
        });
        
        btnRemove = new JButton();
        btnRemove.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		int i = listSources.getSelectedIndex();
        		listModel.remove(i);
        	}
        });
        
        btnBrowse = new JButton();
        btnBrowse.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
            	JFileChooser fc = new JFileChooser();
        		fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        		int returnVal = fc.showDialog(UIView.this, "Set destination");
        		if (returnVal == JFileChooser.APPROVE_OPTION) {
        			txtDestination.setText(fc.getSelectedFile().toString());
        		}
            }
        });
        
        btnSave = new JButton();
        btnSave.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        	}
        });
        
        btnRun = new JButton();
        btnRun.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        	}
        });
        
        

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelSettings.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SETTINGS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 14))); // NOI18N
        panelSettings.setFont(new Font("Helvetica Neue", Font.PLAIN, 16)); // NOI18N

        lblSchedSync.setFont(new Font("Helvetica Neue", Font.PLAIN, 14)); // NOI18N
        lblSchedSync.setText("Scheduled sync:");

        grpRadioSyncSwitch.add(radioOn);
        radioOn.setFont(new Font("Helvetica Neue", Font.PLAIN, 18)); // NOI18N
        radioOn.setText("ON");

        grpRadioSyncSwitch.add(radioOff);
        radioOff.setFont(new Font("Helvetica Neue", Font.PLAIN, 18)); // NOI18N
        radioOff.setText("OFF");

        jXDatePicker.setFont(new Font("Helvetica Neue", 0, 14)); // NOI18N

        spinTime.setFont(new Font("Helvetica Neue", 0, 14)); // NOI18N
        spinTime.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1444176000000L), null, null, java.util.Calendar.MINUTE));
        spinTime.setEditor(new JSpinner.DateEditor(spinTime, "h:mm a"));

        lblDate.setFont(new Font("Helvetica Neue", Font.PLAIN, 13)); // NOI18N
        lblDate.setText("Date:");

        lblTime.setFont(new Font("Helvetica Neue", Font.PLAIN, 13)); // NOI18N
        lblTime.setText("Time:");

        panelFreq.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Frequency", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 12))); // NOI18N
        panelFreq.setLocation(new java.awt.Point(-32267, -32677));

        grpRadioFreq.add(radioDaily);
        radioDaily.setFont(new Font("Helvetica Neue", Font.PLAIN, 13)); // NOI18N
        radioDaily.setText("Daily");

        grpRadioFreq.add(radioWeekly);
        radioWeekly.setFont(new Font("Helvetica Neue", Font.PLAIN, 13)); // NOI18N
        radioWeekly.setText("Weekly");

        grpRadioFreq.add(radioMonthly);
        radioMonthly.setFont(new Font("Helvetica Neue", Font.PLAIN, 13)); // NOI18N
        radioMonthly.setText("Monthly");

        javax.swing.GroupLayout gl_panelFreq = new javax.swing.GroupLayout(panelFreq);
        gl_panelFreq.setHorizontalGroup(
        	gl_panelFreq.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_panelFreq.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(radioDaily)
        			.addPreferredGap(ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
        			.addComponent(radioWeekly)
        			.addGap(18)
        			.addComponent(radioMonthly)
        			.addContainerGap())
        );
        gl_panelFreq.setVerticalGroup(
        	gl_panelFreq.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_panelFreq.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(gl_panelFreq.createParallelGroup(Alignment.BASELINE)
        				.addComponent(radioMonthly)
        				.addComponent(radioDaily)
        				.addComponent(radioWeekly))
        			.addContainerGap(10, Short.MAX_VALUE))
        );
        panelFreq.setLayout(gl_panelFreq);

        javax.swing.GroupLayout gl_panelSettings = new javax.swing.GroupLayout(panelSettings);
        gl_panelSettings.setHorizontalGroup(
        	gl_panelSettings.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_panelSettings.createSequentialGroup()
        			.addGroup(gl_panelSettings.createParallelGroup(Alignment.LEADING)
        				.addGroup(gl_panelSettings.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(lblSchedSync)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(radioOn)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(radioOff))
        				.addGroup(gl_panelSettings.createSequentialGroup()
        					.addGap(33)
        					.addGroup(gl_panelSettings.createParallelGroup(Alignment.LEADING, false)
        						.addGroup(gl_panelSettings.createSequentialGroup()
        							.addComponent(lblDate)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(jXDatePicker, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(lblTime))
        						.addComponent(panelFreq, GroupLayout.PREFERRED_SIZE, 272, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(spinTime, GroupLayout.PREFERRED_SIZE, 149, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(207, Short.MAX_VALUE))
        );
        gl_panelSettings.setVerticalGroup(
        	gl_panelSettings.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_panelSettings.createSequentialGroup()
        			.addGroup(gl_panelSettings.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblSchedSync)
        				.addComponent(radioOn)
        				.addComponent(radioOff))
        			.addGap(18)
        			.addGroup(gl_panelSettings.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jXDatePicker, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblDate)
        				.addComponent(lblTime)
        				.addComponent(spinTime, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addComponent(panelFreq, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(25, Short.MAX_VALUE))
        );
        panelSettings.setLayout(gl_panelSettings);

        panelBackup.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BACKUP", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 14))); // NOI18N
        panelBackup.setFont(new Font("Helvetica Neue", Font.PLAIN, 16)); // NOI18N

        lblSources.setFont(new Font("Helvetica Neue", Font.PLAIN, 14)); // NOI18N
        lblSources.setText("Source File(s) / Folder(s):");

        lblDestination.setFont(new Font("Helvetica Neue", Font.PLAIN, 14)); // NOI18N
        lblDestination.setText("Destination:");

        txtDestination.setFont(new Font("Helvetica Neue", Font.PLAIN, 14)); // NOI18N
        txtDestination.setText("C:\\file\\path\\or\\cloud\\provider\\info");
        txtDestination.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
            }
        });

        lblDestNote.setFont(new Font("Helvetica Neue", Font.PLAIN, 12)); // NOI18N
        lblDestNote.setText("A zip file containing all backup data will be stored at this location");
        
        btnAddFile.setFont(new Font("Helvetica Neue", Font.PLAIN, 14)); // NOI18N
        btnAddFile.setText("Add File");

        btnAddFolder.setFont(new Font("Helvetica Neue", Font.PLAIN, 14)); // NOI18N
        btnAddFolder.setText("Add Folder");

        btnRemove.setFont(new Font("Helvetica Neue", Font.PLAIN, 14)); // NOI18N
        btnRemove.setText("Remove Selection");

        btnBrowse.setFont(new Font("Helvetica Neue", Font.PLAIN, 14)); // NOI18N
        btnBrowse.setText("Browse...");

        btnSave.setFont(new Font("Helvetica Neue", Font.PLAIN, 15)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.setPreferredSize(new Dimension(73, 45));
        btnSave.setMinimumSize(new Dimension(73, 45));
        btnSave.setMaximumSize(new Dimension(73, 45));
        
        btnRun.setFont(new Font("Helvetica Neue", Font.PLAIN, 15));
        btnRun.setText("RUN");
        btnRun.setPreferredSize(new Dimension(73, 45));
        btnRun.setMinimumSize(new Dimension(73, 45));
        btnRun.setMaximumSize(new Dimension(73, 45));
        
        scrollStatus.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Status", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 12))); // NOI18N
        
        panelNameBackup.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Name of Backup", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 12))); // NOI18N

        txtNameBackup.setHorizontalAlignment(JTextField.CENTER);
        txtNameBackup.setText("backup-m-d-yy");

        javax.swing.GroupLayout gl_panelNameBackup = new javax.swing.GroupLayout(panelNameBackup);
        panelNameBackup.setLayout(gl_panelNameBackup);
        gl_panelNameBackup.setHorizontalGroup(
            gl_panelNameBackup.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtNameBackup, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
        );
        gl_panelNameBackup.setVerticalGroup(
            gl_panelNameBackup.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gl_panelNameBackup.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txtNameBackup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        
        javax.swing.GroupLayout gl_panelBackup = new javax.swing.GroupLayout(panelBackup);
        gl_panelBackup.setHorizontalGroup(
        	gl_panelBackup.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_panelBackup.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(gl_panelBackup.createParallelGroup(Alignment.LEADING)
        				.addGroup(gl_panelBackup.createSequentialGroup()
        					.addGroup(gl_panelBackup.createParallelGroup(Alignment.LEADING)
        						.addGroup(gl_panelBackup.createSequentialGroup()
        							.addPreferredGap(ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
        							.addGroup(gl_panelBackup.createParallelGroup(Alignment.LEADING)
        								.addGroup(gl_panelBackup.createSequentialGroup()
        									.addGroup(gl_panelBackup.createParallelGroup(Alignment.LEADING)
        										.addComponent(scrollSources, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 288, GroupLayout.PREFERRED_SIZE)
        										.addComponent(txtDestination, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 288, GroupLayout.PREFERRED_SIZE))
        									.addPreferredGap(ComponentPlacement.UNRELATED)
        									.addGroup(gl_panelBackup.createParallelGroup(Alignment.LEADING)
        										.addComponent(btnAddFolder, GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        										.addComponent(btnAddFile, GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        										.addGroup(gl_panelBackup.createSequentialGroup()
        											.addGroup(gl_panelBackup.createParallelGroup(Alignment.TRAILING, false)
        												.addComponent(btnBrowse, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        												.addComponent(btnRemove, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        											.addGap(9))))
        								.addGroup(gl_panelBackup.createSequentialGroup()
        									.addGap(6)
        									.addComponent(lblDestNote, GroupLayout.PREFERRED_SIZE, 405, GroupLayout.PREFERRED_SIZE))))
        						.addComponent(scrollStatus, GroupLayout.PREFERRED_SIZE, 466, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addGroup(gl_panelBackup.createParallelGroup(Alignment.TRAILING, false)
        						.addComponent(panelNameBackup, GroupLayout.PREFERRED_SIZE, 164, GroupLayout.PREFERRED_SIZE)
        						.addGroup(gl_panelBackup.createSequentialGroup()
        							.addComponent(btnSave, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(btnRun, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        							.addGap(6)))
        					.addPreferredGap(ComponentPlacement.RELATED))
        				.addComponent(lblSources)
        				.addComponent(lblDestination))
        			.addGap(18))
        );
        gl_panelBackup.setVerticalGroup(
        	gl_panelBackup.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_panelBackup.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(lblSources)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(gl_panelBackup.createParallelGroup(Alignment.LEADING)
        				.addComponent(scrollSources, GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
        				.addGroup(gl_panelBackup.createParallelGroup(Alignment.BASELINE)
        					.addComponent(panelNameBackup, GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
        					.addGroup(gl_panelBackup.createSequentialGroup()
        						.addComponent(btnAddFile)
        						.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(btnAddFolder)
        						.addPreferredGap(ComponentPlacement.RELATED)
        						.addComponent(btnRemove))))
        			.addGroup(gl_panelBackup.createParallelGroup(Alignment.LEADING, false)
        				.addGroup(gl_panelBackup.createSequentialGroup()
        					.addGap(25)
        					.addComponent(lblDestination)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(gl_panelBackup.createParallelGroup(Alignment.BASELINE)
        						.addComponent(txtDestination, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(btnBrowse))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(lblDestNote)
        					.addGap(25)
        					.addComponent(scrollStatus, GroupLayout.PREFERRED_SIZE, 71, GroupLayout.PREFERRED_SIZE)
        					.addContainerGap())
        				.addGroup(Alignment.TRAILING, gl_panelBackup.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addGroup(gl_panelBackup.createParallelGroup(Alignment.BASELINE)
        						.addComponent(btnRun, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
        						.addComponent(btnSave, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE))
        					.addGap(11))))
        );
        gl_panelBackup.linkSize(SwingConstants.HORIZONTAL, new Component[] {btnAddFile, btnAddFolder, btnRemove});
        
        scrollSources.setViewportView(listSources);
        panelBackup.setLayout(gl_panelBackup);

        lblAppTitle.setFont(new Font("Helvetica Neue", Font.PLAIN, 15)); // NOI18N
        lblAppTitle.setText("    Mirror Machine (Name TBD)");
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(panelSettings, GroupLayout.PREFERRED_SIZE, 679, GroupLayout.PREFERRED_SIZE)
        						.addComponent(panelBackup, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 679, GroupLayout.PREFERRED_SIZE))
        					.addContainerGap())
        				.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        					.addComponent(lblAppTitle)
        					.addGap(15))))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(lblAppTitle, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
        			.addGap(12)
        			.addComponent(panelSettings, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
        			.addComponent(panelBackup, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ButtonGroup grpRadioSyncSwitch;
    private ButtonGroup grpRadioFreq;
    private DefaultListModel listModel;
    private JButton btnAddFile;
    private JButton btnAddFolder;
    private JButton btnRemove;
    private JButton btnBrowse;
    private JButton btnSave;
    private JButton btnRun;
    private JLabel lblAppTitle;
    private JLabel lblSchedSync;
    private JLabel lblSources;
    private JLabel lblDestination;
    private JLabel lblDestNote;
    private JLabel lblDate;
    private JLabel lblTime;
    private JPanel panelSettings;
    private JPanel panelBackup;
    private JPanel panelNameBackup;
    private JPanel panelFreq;
    private JRadioButton radioOn;
    private JRadioButton radioOff;
    private JRadioButton radioDaily;
    private JRadioButton radioWeekly;
    private JRadioButton radioMonthly;
    private JScrollPane scrollSources;
    private JScrollPane scrollStatus;
    private JSpinner spinTime;
    private JTextField txtDestination;
    private JTextField txtNameBackup;
    private JXDatePicker jXDatePicker;
    private JMenuBar menuBar;
    private JMenu menuOpen;
    private JMenuItem menuItemLog;
    private JMenuItem menuItemManual;
    private JList listSources;
>>>>>>> branch 'feature-ui#5' of git@github.com:codingvirtual/CSC478B.git
}
